---
title: Nicolas_Roelandt_resume
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles_html.css', 'resume']
    # css: ['css/custom_resume.css', 'css/styles_pdf.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
params:
  doctype: "HTML" # "PDF" or "HTML" is automatically updated in update_resume.R 
  author: "Nicolas Roelandt"
  city: |
    315 chemin vieux  
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;42520 Maclas, France
  tel: "+33642404255"
  mail: "nicolas@roelandt.fr"
  github: "Bakaniko"
  blog: "roelandtn.frama.io"
  blog_link: "https://roelandtn.frama.io/"
  linkedin: "nicolasroelandt"
  abstract: "Analyste de données géospatiales"
  
author: "`r params$author`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

#load packages
library(glue)

#source helper functions
source('helper_functions.R')

position_data <- read.csv('./data/position_data.csv', stringsAsFactors = F)
skill_data <- read.csv('./data/skill_data.csv', stringsAsFactors = F)
```


Aside
================================================================================


Contact {#contact}
--------------------------------------------------------------------------------

```{r contactinfo}

# Adjust contact info based on document type - html has link while pdf does not
if(params$doctype == "HTML") {
  glue::glue('
    - <i class="fa fa-map-marked-alt"></i> {params$city}
    - <i class="fa fa-phone"></i> <a href="tel:{params$tel}">{params$tel}</a>
    - <i class="fa fa-envelope"></i> {params$mail}
    - <i class="fa fa-globe"></i> [{params$blog}]({params$blog_link})
    - <i class="fa fa-github"></i> [github.com/{params$github}](https://github.com/{params$github})
    - <i class="fab fa-linkedin-in"></i> [linkedin.com/{params$linkedin}](https://www.linkedin.com/in/{params$linkedin}/)
  ')
} 

if(params$doctype == "PDF") {
  glue::glue('
    - <i class="fa fa-map-marked-alt"></i> {params$city}
    - <i class="fa fa-phone"></i> {params$tel}
    - <i class="fa fa-envelope"></i> {params$mail}
    - <i class="fa fa-globe"></i> {params$blog}
    - <i class="fa fa-github"></i> github.com/{params$github}
    - <i class="fab fa-linkedin-in"></i> linkedin.com/{params$linkedin}
  ')
}

```



```{r download}
# if doctype is html add link to download a pdf version
if(params$doctype == "HTML"){
  cat("[<i class='fas fa-download'></i> Download as a PDF](https://github.com/bakaniko/resume/raw/main/Nicolas_Roelandt_resume.pdf)")
}

```

<br>


Compétence techniques {#skills}
--------------------------------------------------------------------------------

```{r codingskills, dev.args = list(bg = 'transparent')}

# function from helper_functions.R
build_skill_bars(skill_data, "Tech")

```

Langues {#languages}
--------------------------------------------------------------------------------

```{r languages, dev.args = list(bg = 'transparent')}

# function from helper_functions.R
build_skill_bars(skill_data, "Languages")

```

Autres informations {#interests}
--------------------------------------------------------------------------------

```{r Interests, dev.args = list(bg = 'transparent')}

# function from helper_functions.R
build_skill_bars(skill_data, "Interests")

```

<br>

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

```{r}

# set disclaimer in bottom right corner based on doctype
if(params$doctype == "HTML") {
  glue::glue("
    Made w/ [**pagedown**](https://github.com/rstudio/pagedown).   
    Source code: [**Github repo**](https://github.com/{params$github}/resume).
  ")
} 
if(params$doctype == "PDF") {
  glue::glue("
    Made w/ **pagedown::html_resume**
    Code: **github.com/{params$github}/resume** 
  ")
}
```


Last updated on `r Sys.Date()`.
<br>
<br>


Main
================================================================================


`r params$author` {#title}
--------------------------------------------------------------------------------

`r params$abstract`



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r education}
print_section(position_data, 'education')
```



Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r jobs}
print_section(position_data, 'work')
```

